import {useEffect,useState} from 'react'
import {Link,useNavigate} from 'react-router-dom'
import {sb} from './supabase'
import {optimizeImage,fmt} from './imagen'
import {api} from './api'
import {Async,useData,useTitle,slugify} from './ui'
import NewsEditor from './NewsEditor'
import {RichEditor,ImgPick} from './Editor'
import {isHtml,sanitize,textToHtml,htmlToText} from './editorUtils'
import {useSeo,SeoPanel,SEO_COLS,isColumnError} from './SeoPanel'
import StatsAdmin from './StatsAdmin'
function Img({onUrl,label,max}){const[p,setP]=useState(null),[st,setSt]=useState('')
 async function pick(e){const f0=e.target.files[0];if(!f0)return;onUrl(null);setP(null);setSt('Optimizando imagen…')
  let r;try{r=await optimizeImage(f0,{maxSide:max||1600})}catch(er){e.target.value='';return setSt('Error: '+er.message)}
  setP(URL.createObjectURL(r.file));setSt('Subiendo imagen…')
  const path=`${Date.now()}-${r.file.name.replace(/[^a-z0-9.]+/gi,'-')}`,{error}=await sb.storage.from('imagenes').upload(path,r.file,{contentType:r.file.type})
  if(error)return setSt('Error al subir la imagen: '+error.message)
  onUrl(sb.storage.from('imagenes').getPublicUrl(path).data.publicUrl);setSt(r.changed?`Imagen optimizada (${fmt(r.before)} → ${fmt(r.after)}) y subida ✔`:'Imagen subida ✔')}
 return <><label>{label||'Imagen principal'}</label><input type="file" accept="image/*" onChange={pick}/>{p&&<img src={p} alt="Vista previa" style={{maxWidth:'100%',maxHeight:180,marginTop:8}}/>}<small className="muted">{st}</small></>}
const Opts=({l,v='id',t='nombre'})=>l.map(x=><option key={x[v]} value={x[v]}>{x[t]}</option>)
const Msg=({m})=>m?<p className={m.err?'err':''} style={m.err?null:{color:'#7ee39a'}}>{m.t}</p>:null
const CATS=[['primera','Primera'],['primera-nacional','Primera Nacional'],['primera-b-metropolitana','Primera B Metropolitana'],['primera-c','Primera C'],['federal-a','Torneo Federal A']]
const fechas=n=>Array.from({length:n},(_,i)=>`Fecha ${i+1}`),KO=['Octavos de final','Cuartos de final','Semifinal','Final']
// Instancias por torneo (se puede editar acá). Torneos que no figuran usan un número de fecha libre.
const INST={'primera-division':[...fechas(16),...KO],'copa-argentina':['32avos de final','16avos de final',...KO],'trofeo-de-campeones':['Final'],'supercopa-argentina':['Final'],'supercopa-internacional':['Final'],'recopa-de-campeones':['Fecha 1','Fecha 2'],'copa-libertadores':['Ronda 2','Ronda 3',...fechas(6),...KO],'copa-sudamericana':[...fechas(6),'Playoff',...KO]}
function ChrForm(){const nav=useNavigate(),o=useData(()=>Promise.all([api.clubs(),api.writers(),api.tournaments()])),[img,setImg]=useState(null),[html,setHtml]=useState(''),[upl,setUpl]=useState(false),[w,setW]=useState(''),[hn,setHn]=useState(''),[an,setAn]=useState(''),[to,setTo]=useState(''),[tt,setTt]=useState(''),[bb,setBb]=useState(''),[busy,setBusy]=useState(false),[m,setM]=useState(null)
 const tn=(o.data?.[2]||[]).find(z=>z.id===to)?.nombre,seo=useSeo({x:null,titulo:tt,bajada:bb,html,img,writer:w,sugTema:hn.trim()&&an.trim()?`${hn.trim()} vs ${an.trim()}`:'',sugTemas:[hn.trim(),an.trim(),tn].filter(Boolean).join(', ')})
 const find=(cl,name)=>cl.find(c=>slugify(c.nombre)===slugify(name||''))
 function onHome(v,cl,wr){const c=find(cl,v),x=c&&wr.find(r=>r.club_id===c.id);if(x)setW(x.id)} // sugiere el cronista del local
 async function club(cl,name,cat){const n=name.trim(),c=find(cl,n);if(c)return c.id
  const sl=slugify(n),ex=await sb.from('clubs').select('id,activo').eq('slug',sl).maybeSingle();if(ex.error)throw ex.error
  if(ex.data){if(!ex.data.activo){const u=await sb.from('clubs').update({activo:true,categoria:cat||null}).eq('id',ex.data.id);if(u.error)throw u.error}return ex.data.id}
  const ins=await sb.from('clubs').insert({nombre:n,slug:sl,activo:true,categoria:cat||null}).select('id').single();if(ins.error)throw ins.error;return ins.data.id} // club nuevo: queda creado y visible en Clubes del panel
 async function save(e,cl){e.preventDefault();if(busy||upl)return;const f=new FormData(e.target),h=f.get('h').trim(),a=f.get('a').trim()
  if(!h||!a)return setM({err:1,t:'Escribí o elegí los dos equipos.'});if(slugify(h)===slugify(a))return setM({err:1,t:'Local y visitante deben ser distintos.'});if(!w)return setM({err:1,t:'Elegí un redactor (o "Redacción Meraki").'})
  if(!htmlToText(html).trim())return setM({err:1,t:'Escribí el contenido de la crónica.'})
  setBusy(true);setM(null)
  try{const hid=await club(cl,h,f.get('ch')),aid=await club(cl,a,f.get('ca')),ins=f.get('i'),fn=ins&&/^Fecha \d+$/.test(ins)?+ins.slice(6):(f.get('n')?+f.get('n'):null)
   const{data,error}=await sb.rpc('publish_chronicle',{p_tournament:f.get('to'),p_fecha_numero:fn,p_instancia:ins||(fn?'Fecha '+fn:null),p_fecha:f.get('d')?new Date(f.get('d')).toISOString():null,p_home:hid,p_away:aid,p_hg:+f.get('hg'),p_ag:+f.get('ag'),p_writer:w,p_titulo:f.get('t'),p_bajada:f.get('b'),p_contenido:sanitize(html),p_imagen:img,p_estado:f.get('est')})
   if(error)throw error
   const u=await sb.from('chronicles').update(seo.cols()).eq('slug',data) // datos SEO sobre la misma crónica recién publicada
   if(u.error){setBusy(false);return setM({err:1,t:`La crónica se publicó (/cronicas/${data}), pero no se guardaron los datos SEO: ${u.error.message}. ${isColumnError(u.error)?'Falta ejecutar migracion-seo-cronicas.sql en Supabase. ':''}No la vuelvas a publicar: completá el SEO desde Contenido → Editar.`})}
   nav('/cronicas/'+data)}
  catch(er){setBusy(false);setM({err:1,t:(er.message||'').includes('ya tiene una crónica')?'Este partido ya tiene una crónica.':(er.message||'Error al publicar')})}}
 return <Async s={o}>{([cl,wr,tl])=>{const slug=tl.find(x=>x.id===to)?.slug,opts=INST[slug];return <form onSubmit={e=>save(e,cl)}><h3>Nueva crónica</h3>
  <label>Torneo</label><select name="to" required value={to} onChange={e=>setTo(e.target.value)}><option value="" disabled>Elegir…</option><Opts l={tl}/></select>
  {opts?<><label>Instancia / fecha</label><select name="i" key={slug} required defaultValue=""><option value="" disabled>Elegir…</option>{opts.map(x=><option key={x}>{x}</option>)}</select></>:<><label>Número de fecha (opcional)</label><input name="n" type="number" min="1"/></>}
  <label>Fecha y hora del partido (opcional)</label><input name="d" type="datetime-local"/>
  <datalist id="clubes-lista">{cl.map(c=><option key={c.id} value={c.nombre}/>)}</datalist>
  <label>Equipo local (elegí de la lista o escribilo)</label><input name="h" list="clubes-lista" required autoComplete="off" value={hn} onChange={e=>{setHn(e.target.value);onHome(e.target.value,cl,wr)}}/>{hn.trim()&&!find(cl,hn)&&<><label>«{hn.trim()}» es un club nuevo: ¿de qué categoría es?</label><select name="ch" required defaultValue=""><option value="" disabled>Elegir…</option>{CATS.map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></>}
  <label>Equipo visitante (elegí de la lista o escribilo)</label><input name="a" list="clubes-lista" required autoComplete="off" value={an} onChange={e=>setAn(e.target.value)}/>{an.trim()&&!find(cl,an)&&<><label>«{an.trim()}» es un club nuevo: ¿de qué categoría es?</label><select name="ca" required defaultValue=""><option value="" disabled>Elegir…</option>{CATS.map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></>}
  <label>Goles local / visitante</label><div style={{display:'flex',gap:8}}><input name="hg" type="number" min="0" defaultValue="0" required/><input name="ag" type="number" min="0" defaultValue="0" required/></div>
  <label>Redactor (se sugiere el del local; podés elegir "Redacción Meraki")</label><select value={w} onChange={e=>setW(e.target.value)} required><option value="" disabled>Elegir…</option><Opts l={wr} t="nombre_visible"/></select>
  <label>Título</label><input name="t" required value={tt} onChange={e=>setTt(e.target.value)}/><label>Bajada</label><input name="b" value={bb} onChange={e=>setBb(e.target.value)}/><label>Contenido</label><RichEditor initial="" onChange={setHtml} onBusy={setUpl}/><ImgPick value={img} onUrl={setImg} onBusy={setUpl}/><SeoPanel s={seo} titulo={tt} img={img}/><label>Estado</label><select name="est"><option value="publicada">publicada</option><option value="borrador">borrador</option></select>
  <Msg m={m}/><p><button className="btn" disabled={busy||upl} style={{border:0,cursor:'pointer'}}>{busy?'Publicando…':upl?'Subiendo imagen…':'Publicar'}</button></p></form>}}</Async>}
async function upImg(file){const r=await optimizeImage(file,{maxSide:600});const path=`escudos/${Date.now()}-${r.file.name.replace(/[^a-z0-9.]+/gi,'-')}`,{error}=await sb.storage.from('imagenes').upload(path,r.file,{contentType:r.file.type});if(error)throw error;return sb.storage.from('imagenes').getPublicUrl(path).data.publicUrl}
function ClubsAdmin(){const[v,setV]=useState(0),s=useData(api.clubs,[v]),[img,setImg]=useState(null),[busy,setBusy]=useState(false),[m,setM]=useState(null)
 async function add(e){e.preventDefault();if(busy)return;const fm=e.target,f=new FormData(fm);setBusy(true);setM(null);const nombre=f.get('n').trim()
  const{error}=await sb.from('clubs').insert({nombre,slug:slugify(f.get('s')||nombre),ciudad:f.get('c'),estadio:f.get('e'),categoria:f.get('k')||null,escudo_url:img});setBusy(false)
  if(error)return setM({err:1,t:error.code==='23505'?'Ya existe un club con ese slug.':error.message});fm.reset();setImg(null);setM({t:'Club guardado.'});setV(x=>x+1)}
 async function setCat(c,v){const{error}=await sb.from('clubs').update({categoria:v||null}).eq('id',c.id);if(error)return setM({err:1,t:error.message});setM({t:`${c.nombre}: categoría actualizada ✔`});setV(x=>x+1)}
 async function del(c){if(!confirm(`¿Eliminar el club "${c.nombre}"?`))return;const{error}=await sb.from('clubs').delete().eq('id',c.id);if(error)return setM({err:1,t:error.code==='23503'?'Este club tiene crónicas o partidos. Eliminalas primero en la pestaña Contenido.':error.message});setM({t:'Club eliminado.'});setV(x=>x+1)}
 async function escudo(c,file){if(!file)return;setM({t:`Optimizando y subiendo escudo de ${c.nombre}…`});try{const url=await upImg(file);const{error}=await sb.from('clubs').update({escudo_url:url}).eq('id',c.id);if(error)throw error;setM({t:`Escudo de ${c.nombre} guardado ✔`});setV(x=>x+1)}catch(er){setM({err:1,t:'Error: '+er.message})}}
 return <div><h3>Clubes y escudos</h3><Msg m={m}/><Async s={s} empty="No hay clubes cargados.">{l=>l.map(c=><div key={c.id} style={{display:'flex',gap:10,alignItems:'center',padding:'8px 0',borderBottom:'1px solid var(--line)'}}>{c.escudo_url?<img src={c.escudo_url} width="32" height="36" alt="" style={{objectFit:'contain'}}/>:<span className="shield" style={{'--c':'#1f6b3a',width:32,height:36}}/>}<span style={{flex:1}}>{c.nombre}{c.es_demo?' (demo)':''}</span><select value={c.categoria||''} onChange={e=>setCat(c,e.target.value)} style={{width:'auto'}}><option value="">sin categoría</option>{CATS.map(([v,n])=><option key={v} value={v}>{n}</option>)}</select><label className="tag" style={{cursor:'pointer',margin:0}}>Cambiar escudo<input type="file" accept="image/*" style={{display:'none'}} onChange={e=>escudo(c,e.target.files[0])}/></label><button className="tag" onClick={()=>del(c)}>Eliminar</button></div>)}</Async>
 <form onSubmit={add}><h3 style={{marginTop:20}}>Nuevo club</h3><label>Nombre</label><input name="n" required/><label>Slug (opcional)</label><input name="s"/><label>Ciudad</label><input name="c"/><label>Estadio</label><input name="e"/><label>Categoría</label><select name="k" defaultValue="primera">{CATS.map(([v,n])=><option key={v} value={v}>{n}</option>)}</select><Img onUrl={setImg} label="Escudo" max={600}/><p><button className="btn" disabled={busy} style={{border:0,cursor:'pointer'}}>{busy?'Guardando…':'Guardar club'}</button></p></form></div>}
function WritersAdmin(){const[v,setV]=useState(0),o=useData(()=>Promise.all([api.clubs(),api.writers()]),[v]),[busy,setBusy]=useState(false),[m,setM]=useState(null)
 async function add(e){e.preventDefault();if(busy)return;const fm=e.target,f=new FormData(fm);setBusy(true);setM(null);const n=f.get('n').trim(),a=f.get('a').trim()
  const{error}=await sb.from('writers').insert({nombre:n,apellido:a,nombre_visible:(f.get('v')||`${n} ${a}`).trim(),club_id:f.get('c')||null,descripcion:f.get('d')});setBusy(false)
  if(error)return setM({err:1,t:error.message});fm.reset();setM({t:'Cronista guardado.'});setV(x=>x+1)}
 async function delW(w){if(!confirm(`¿Eliminar a ${w.nombre_visible}?`))return;const{error}=await sb.from('writers').delete().eq('id',w.id);if(error)return setM({err:1,t:error.code==='23503'?'Este cronista tiene crónicas. Eliminalas primero en Contenido.':error.message});setV(x=>x+1)}
 return <Async s={o}>{([cl,wr])=><div><h3>Cronistas</h3><form onSubmit={add}><label>Nombre</label><input name="n" required/><label>Apellido</label><input name="a" required/><label>Nombre visible (opcional)</label><input name="v"/><label>Club del que es cronista</label><select name="c"><option value="">—</option><Opts l={cl}/></select><label>Descripción (opcional)</label><input name="d"/><Msg m={m}/><p><button className="btn" disabled={busy} style={{border:0,cursor:'pointer'}}>{busy?'Guardando…':'Guardar cronista'}</button></p></form><h3>Cargados</h3>{wr.map(w=><div key={w.id} style={{display:'flex',gap:8,alignItems:'center',padding:'6px 0'}}><span style={{flex:1}}>{w.nombre_visible}{w.es_demo?' (demo)':''} — {cl.find(c=>c.id===w.club_id)?.nombre||'sin club'}</span><button className="tag" onClick={()=>delW(w)}>Eliminar</button></div>)}</div>}</Async>}
function EditForm({t,x,done}){const[img,setImg]=useState(null),[busy,setBusy]=useState(false),[m,setM]=useState(null),[html,setHtml]=useState(()=>isHtml(x.contenido)?sanitize(x.contenido):textToHtml(x.contenido)),[upl,setUpl]=useState(false),[tt,setTt]=useState(x.titulo||''),[bb,setBb]=useState(x.bajada||''),lo=useData(()=>t==='c'?Promise.all([api.clubs(),api.tournaments()]):Promise.resolve([[],[]]))
 const seo=useSeo({x,titulo:tt,bajada:bb,html,img:img||x.imagen_url,writer:x.writer_id,lists:lo.data?{cl:lo.data[0],to:lo.data[1]}:{cl:[],to:[]}})
 async function save(e){e.preventDefault();if(busy||upl)return;const f=new FormData(e.target)
  if(!htmlToText(html).trim())return setM({err:1,t:'Escribí el contenido.'})
  setBusy(true);setM(null)
  const u={titulo:f.get('t'),bajada:f.get('b'),contenido:sanitize(html),estado:f.get('e')};if(img)u.imagen_url=img
  if(t==='c'&&u.estado==='publicada'&&!x.publicada_at)u.publicada_at=new Date().toISOString()
  const tbl=t==='n'?'news':'chronicles',run=r=>sb.from(tbl).update(r).eq('id',x.id)
  let r=await run(t==='c'?{...u,...seo.cols()}:u),legacy=false
  if(t==='c'&&isColumnError(r.error)){r=await run(u);legacy=!r.error} // base sin columnas SEO: se guarda lo básico
  setBusy(false);if(r.error)return setM({err:1,t:r.error.message})
  if(legacy)return setM({err:1,t:'Guardada, pero la base todavía no tiene los campos SEO. Ejecutá migracion-seo-cronicas.sql en Supabase y volvé a guardar.'});done()}
 return <form onSubmit={save} style={{background:'var(--bg2)',padding:12,margin:'8px 0'}}><label>Título</label><input name="t" value={tt} onChange={e=>setTt(e.target.value)} required/><label>Bajada</label><input name="b" value={bb} onChange={e=>setBb(e.target.value)}/><label>Contenido</label><RichEditor initial={html} onChange={setHtml} onBusy={setUpl}/><Img onUrl={setImg} label="Cambiar imagen (opcional)"/>{t==='c'&&<SeoPanel s={seo} titulo={tt} img={img||x.imagen_url}/>}<label>Estado</label><select name="e" defaultValue={x.estado}><option value="borrador">borrador</option><option value="publicada">publicada</option></select><Msg m={m}/><p><button className="btn" disabled={busy||upl} style={{border:0,cursor:'pointer'}}>{busy?'Guardando…':upl?'Subiendo imagen…':'Guardar cambios'}</button> <button type="button" className="tag" onClick={done}>Cancelar</button></p></form>}
function ContentAdmin(){const[v,setV]=useState(0),[m,setM]=useState(null),[ed,setEd]=useState(null),s=useData(async()=>{const[n,c]=await Promise.all([sb.from('news').select('*').order('created_at',{ascending:false}).limit(50),sb.from('chronicles').select('*').order('created_at',{ascending:false}).limit(50)]);if(n.error)throw n.error;if(c.error)throw c.error;return{n:n.data,c:c.data}},[v])
 async function run(p,ok){const{error}=await p;if(error)return setM({err:1,t:error.message});setM({t:ok});setV(x=>x+1)}
 const del=(t,x)=>confirm(`¿Eliminar "${x.titulo}"? No se puede deshacer.`)&&run(t==='n'?sb.from('news').delete().eq('id',x.id):sb.from('matches').delete().eq('id',x.match_id),'Eliminado.')
 const tog=x=>run(sb.from('news').update({estado:x.estado==='publicada'?'borrador':'publicada'}).eq('id',x.id),'Estado actualizado.')
 const row=(x,t)=><div key={x.id}><div style={{display:'flex',gap:8,alignItems:'center',flexWrap:'wrap',padding:'8px 0',borderBottom:'1px solid var(--line)'}}><span style={{flex:1,minWidth:150}}>{x.titulo} <small className="muted">({x.estado})</small></span><button className="tag" onClick={()=>setEd(ed?.x.id===x.id?null:{t,x})}>Editar</button>{t==='n'&&<button className="tag" onClick={()=>tog(x)}>{x.estado==='publicada'?'Pasar a borrador':'Publicar'}</button>}<button className="tag" onClick={()=>del(t,x)}>Eliminar</button></div>{ed?.x.id===x.id&&(t==='n'?<NewsEditor x={x} done={()=>{setEd(null);setV(y=>y+1)}}/>:<EditForm t={t} x={x} done={()=>{setEd(null);setV(y=>y+1)}}/>)}</div>
 return <div><h3>Noticias</h3><Msg m={m}/><Async s={s}>{d=><>{d.n.map(x=>row(x,'n'))}{!d.n.length&&<p className="muted">No hay noticias.</p>}<h3 style={{marginTop:20}}>Crónicas</h3>{d.c.map(x=>row(x,'c'))}{!d.c.length&&<p className="muted">No hay crónicas.</p>}</>}</Async></div>}
function InterviewForm(){const[img,setImg]=useState(null),[busy,setBusy]=useState(false),[m,setM]=useState(null)
 async function save(e){e.preventDefault();if(busy)return;const fm=e.target,f=new FormData(fm);setBusy(true);setM(null);const titulo=f.get('t').trim(),slug=slugify(titulo)
  const{error}=await sb.from('interviews').insert({titulo,slug,bajada:f.get('b'),contenido:f.get('c'),imagen_url:img,entrevistado:f.get('p'),tipo_entrevistado:f.get('k'),enlace_url:f.get('l')||null,estado:f.get('e')});setBusy(false)
  if(error)return setM({err:1,t:error.code==='23505'?'Ya existe una entrevista con ese título.':error.message});fm.reset();setImg(null);setM({t:'Entrevista guardada. URL: /entrevistas/'+slug})}
 return <form onSubmit={save}><h3>Nueva entrevista</h3><label>Título</label><input name="t" required/><label>Entrevistado/a</label><input name="p" required/><label>Tipo</label><select name="k"><option value="jugador">jugador</option><option value="entrenador">entrenador</option><option value="dirigente">dirigente</option><option value="periodista">periodista</option><option value="otra">otra personalidad</option></select><label>Link de la entrevista (YouTube, etc.)</label><input name="l" placeholder="https://..."/><label>Bajada</label><input name="b"/><label>Texto (opcional)</label><textarea name="c" rows="5"/><Img onUrl={setImg}/><label>Estado</label><select name="e"><option value="publicada">publicada</option><option value="borrador">borrador</option></select><Msg m={m}/><p><button className="btn" disabled={busy} style={{border:0,cursor:'pointer'}}>{busy?'Guardando…':'Guardar entrevista'}</button></p></form>}
const KEYS=[['quienes_somos','Texto de ¿Quiénes somos?',1],['afa_texto','Texto de la página AFA',1],['youtube_url','Link del canal de YouTube',0],['instagram_url','Link de Instagram',0],['tiktok_url','Link de TikTok',0],['x_url','Link de X (Twitter)',0],['facebook_url','Link de Facebook',0]]
function SettingsAdmin(){const[v,setV]=useState(0),s=useData(api.settings,[v]),[busy,setBusy]=useState(false),[m,setM]=useState(null),[logo,setLogo]=useState(null)
 async function save(e){e.preventDefault();if(busy)return;const f=new FormData(e.target);setBusy(true);setM(null);const rows=KEYS.map(([k])=>({key:k,value:f.get(k)||''}));if(logo)rows.push({key:'afa_logo',value:logo})
  const{error}=await sb.from('site_settings').upsert(rows);setBusy(false);if(error)return setM({err:1,t:error.message});setM({t:'Guardado ✔'});setV(x=>x+1)}
 return <Async s={s}>{c=><form onSubmit={save} key={v}><h3>Textos y sitio</h3>{KEYS.map(([k,l,big])=><div key={k}><label>{l}</label>{big?<textarea name={k} rows="5" defaultValue={c[k]||''}/>:<input name={k} defaultValue={c[k]||''} placeholder="https://..."/>}</div>)}<Img onUrl={setLogo} label="Logo de la AFA" max={800}/>{c.afa_logo&&<p className="muted">Ya hay un logo cargado. Si subís otro, lo reemplaza.</p>}<Msg m={m}/><p><button className="btn" disabled={busy} style={{border:0,cursor:'pointer'}}>{busy?'Guardando…':'Guardar'}</button></p></form>}</Async>}
const DIAS=['Lunes','Martes','Miércoles','Jueves','Viernes','Sábado','Domingo']
const RK=[['nombre','Nombre de la radio',0],['titulo_portada','Título principal de la portada',0],['texto_portada','Texto de presentación de la portada',1],['descripcion','Descripción de la radio',1],['stream_url','Link para escuchar en vivo',0],['instagram_url','Instagram de FM Meraki',0],['facebook_url','Facebook de FM Meraki',0],['youtube_url','YouTube de FM Meraki',0],['tiktok_url','TikTok de FM Meraki',0],['x_url','X / Twitter de FM Meraki',0],['whatsapp','WhatsApp (número o link)',0],['contacto','Información de contacto (mail, dirección…)',1]]
function RadioAdmin(){const[v,setV]=useState(0),s=useData(api.radio,[v]),[busy,setBusy]=useState(false),[m,setM]=useState(null),[logo,setLogo]=useState(null)
 async function save(e){e.preventDefault();if(busy)return;const f=new FormData(e.target);setBusy(true);setM(null);const rows=RK.map(([k])=>({key:k,value:f.get(k)||''}));if(logo)rows.push({key:'logo',value:logo})
  const{error}=await sb.from('radio_settings').upsert(rows);setBusy(false);if(error)return setM({err:1,t:error.message});setM({t:'Guardado ✔'});setV(x=>x+1)}
 return <Async s={s}>{c=><form onSubmit={save} key={v}><h3>FM Meraki: configuración de la radio</h3>{RK.map(([k,l,big])=><div key={k}><label>{l}</label>{big?<textarea name={k} rows="4" defaultValue={c[k]||''}/>:<input name={k} defaultValue={c[k]||''}/>}</div>)}<Img onUrl={setLogo} label="Logo de la radio" max={800}/>{c.logo&&<p className="muted">Ya hay un logo cargado. Si subís otro, lo reemplaza.</p>}<Msg m={m}/><p><button className="btn" disabled={busy} style={{border:0,cursor:'pointer'}}>{busy?'Guardando…':'Guardar'}</button></p></form>}</Async>}
const PF=[['conductores','Conductores'],['instagram_url','Instagram del programa'],['facebook_url','Facebook del programa'],['youtube_url','YouTube del programa'],['tiktok_url','TikTok del programa'],['x_url','X / Twitter del programa'],['whatsapp','WhatsApp / contacto del programa'],['link_externo','Link externo'],['emoji','Emoji del programa destacado (escribilo o pegalo con el teclado de emojis)']]
function ProgramForm({x,n,done}){const[img,setImg]=useState(null),[busy,setBusy]=useState(false),[m,setM]=useState(null)
 async function save(e){e.preventDefault();if(busy)return;const f=new FormData(e.target);setBusy(true);setM(null);const nombre=f.get('nombre').trim()
  const r={nombre,slug:slugify(f.get('slug')||nombre),descripcion:f.get('descripcion')||null,activo:f.get('activo')==='on',destacado:f.get('destacado')==='on'};PF.forEach(([k])=>{r[k]=f.get(k)||null});r.emoji=(f.get('emoji')||'').trim()||null;r.quienes_somos=f.get('quienes_somos')||null;if(img)r.logo_url=img;if(!x)r.orden=n
  const{error}=await(x?sb.from('programs').update(r).eq('id',x.id):sb.from('programs').insert(r));setBusy(false);if(error)return setM({err:1,t:error.code==='23505'?'Ya existe un programa con ese slug.':error.message});done()}
 const ck={width:'auto',marginRight:8}
 return <form onSubmit={save} style={{background:'var(--bg2)',padding:12,margin:'8px 0'}}><label>Nombre</label><input name="nombre" defaultValue={x?.nombre||''} required/><label>Slug (opcional: es la dirección /programas/…)</label><input name="slug" defaultValue={x?.slug||''} readOnly={x?.slug==='meraki-futbol'}/>{PF.map(([k,l])=><div key={k}><label>{l}</label><input name={k} defaultValue={x?.[k]||''} style={k==='emoji'?{fontSize:24}:null}/></div>)}<label>Descripción</label><textarea name="descripcion" rows="5" defaultValue={x?.descripcion||''}/><label>¿Quiénes somos? de este programa</label><textarea name="quienes_somos" rows="6" defaultValue={x?.quienes_somos||''}/><Img onUrl={setImg} label="Logo / imagen del programa"/>
  <label><input type="checkbox" name="activo" style={ck} defaultChecked={x?x.activo:true}/>Activo (se ve en la web)</label><label><input type="checkbox" name="destacado" style={ck} defaultChecked={!!x?.destacado}/>Destacado (aparece en la portada)</label><Msg m={m}/><p><button className="btn" disabled={busy} style={{border:0,cursor:'pointer'}}>{busy?'Guardando…':'Guardar programa'}</button> <button type="button" className="tag" onClick={done}>Cancelar</button></p></form>}
function ProgramsAdmin(){const[v,setV]=useState(0),[m,setM]=useState(null),[ed,setEd]=useState(null),s=useData(async()=>{const r=await sb.from('programs').select('*').order('orden').order('nombre');if(r.error)throw r.error;return r.data},[v])
 const run=async(p,ok)=>{const{error}=await p;if(error)return setM({err:1,t:error.message});setM(ok?{t:ok}:null);setV(x=>x+1)}
 const upd=(x,u)=>run(sb.from('programs').update(u).eq('id',x.id))
 const del=x=>confirm(`¿Eliminar "${x.nombre}" y sus bloques de la grilla? No se puede deshacer.`)&&run(sb.from('programs').delete().eq('id',x.id),'Programa eliminado.')
 async function move(l,i,d){const a=[...l],j=i+d;if(j<0||j>=a.length)return;[a[i],a[j]]=[a[j],a[i]];const rs=await Promise.all(a.map((p,k)=>sb.from('programs').update({orden:k}).eq('id',p.id)));const e=rs.find(r=>r.error);if(e)return setM({err:1,t:e.error.message});setV(x=>x+1)}
 const done=()=>{setEd(null);setV(x=>x+1)}
 return <div><h3>Programas</h3><Msg m={m}/><p><button className="tag" onClick={()=>setEd(ed==='new'?null:'new')}>+ Nuevo programa</button></p>{ed==='new'&&<ProgramForm n={s.data?.length||0} done={done}/>}
  <Async s={s} empty="Todavía no hay programas.">{l=>l.map((x,i)=><div key={x.id}><div style={{display:'flex',gap:8,alignItems:'center',flexWrap:'wrap',padding:'8px 0',borderBottom:'1px solid var(--line)'}}><span style={{flex:1,minWidth:150}}>{x.nombre} <small className="muted">{!x.activo&&'(inactivo) '}{x.destacado&&'(destacado) '}{x.es_demo&&'(demo)'}</small></span><button className="tag" onClick={()=>move(l,i,-1)}>↑</button><button className="tag" onClick={()=>move(l,i,1)}>↓</button><button className="tag" onClick={()=>setEd(ed?.id===x.id?null:x)}>Editar</button><button className="tag" onClick={()=>upd(x,{activo:!x.activo})}>{x.activo?'Desactivar':'Activar'}</button><button className="tag" onClick={()=>upd(x,{destacado:!x.destacado})}>{x.destacado?'Quitar destacado':'Destacar'}</button><button className="tag" onClick={()=>del(x)}>Eliminar</button></div>{ed?.id===x.id&&<ProgramForm x={x} done={done}/>}</div>)}</Async></div>}
function BlockForm({x,progs,done}){const[busy,setBusy]=useState(false),[m,setM]=useState(null)
 async function save(e){e.preventDefault();if(busy)return;const f=new FormData(e.target),hi=f.get('hi'),hf=f.get('hf');if(hf<=hi)return setM({err:1,t:'La hora de fin tiene que ser posterior al inicio.'});setBusy(true);setM(null)
  const r={dia:+f.get('dia'),hora_inicio:hi,hora_fin:hf,program_id:f.get('p'),activo:f.get('activo')==='on'}
  const{error}=await(x?sb.from('schedule').update(r).eq('id',x.id):sb.from('schedule').insert(r));setBusy(false);if(error)return setM({err:1,t:error.message});done()}
 return <form onSubmit={save} style={{background:'var(--bg2)',padding:12,margin:'8px 0'}}><label>Día</label><select name="dia" defaultValue={x?.dia||1}>{DIAS.map((d,i)=><option key={d} value={i+1}>{d}</option>)}</select><label>Hora de inicio</label><input name="hi" type="time" required defaultValue={String(x?.hora_inicio||'').slice(0,5)}/><label>Hora de fin</label><input name="hf" type="time" required defaultValue={String(x?.hora_fin||'').slice(0,5)}/><label>Programa</label><select name="p" required defaultValue={x?.program_id||''}><option value="" disabled>Elegir…</option><Opts l={progs}/></select>
  <label><input type="checkbox" name="activo" style={{width:'auto',marginRight:8}} defaultChecked={x?x.activo:true}/>Activo</label><Msg m={m}/><p><button className="btn" disabled={busy} style={{border:0,cursor:'pointer'}}>{busy?'Guardando…':'Guardar bloque'}</button> <button type="button" className="tag" onClick={done}>Cancelar</button></p></form>}
function ScheduleAdmin(){const[v,setV]=useState(0),[m,setM]=useState(null),[ed,setEd]=useState(null),s=useData(async()=>{const[b,p]=await Promise.all([sb.from('schedule').select('*').order('dia').order('hora_inicio'),sb.from('programs').select('id,nombre').order('orden')]);if(b.error)throw b.error;if(p.error)throw p.error;return{b:b.data,p:p.data}},[v])
 const run=async(q,ok)=>{const{error}=await q;if(error)return setM({err:1,t:error.message});setM(ok?{t:ok}:null);setV(x=>x+1)}
 const done=()=>{setEd(null);setV(x=>x+1)},nm=(d,id)=>d.p.find(p=>p.id===id)?.nombre||'?'
 return <div><h3>Grilla</h3><Msg m={m}/><p><button className="tag" onClick={()=>setEd(ed==='new'?null:'new')}>+ Nuevo bloque</button></p>
  <Async s={s}>{d=><>{ed==='new'&&<BlockForm progs={d.p} done={done}/>}{!d.b.length&&<p className="muted">Todavía no hay bloques de programación.</p>}{DIAS.map((dn,i)=>{const bl=d.b.filter(x=>x.dia===i+1);return bl.length>0&&<div key={dn}><h3 style={{marginTop:14}}>{dn}</h3>{bl.map(x=><div key={x.id}><div style={{display:'flex',gap:8,alignItems:'center',flexWrap:'wrap',padding:'8px 0',borderBottom:'1px solid var(--line)'}}><span style={{flex:1,minWidth:150}}>{String(x.hora_inicio).slice(0,5)} - {String(x.hora_fin).slice(0,5)} · {nm(d,x.program_id)} <small className="muted">{!x.activo&&'(inactivo)'}</small></span><button className="tag" onClick={()=>setEd(ed?.id===x.id?null:x)}>Editar</button><button className="tag" onClick={()=>run(sb.from('schedule').update({activo:!x.activo}).eq('id',x.id))}>{x.activo?'Desactivar':'Activar'}</button><button className="tag" onClick={()=>confirm('¿Eliminar este bloque?')&&run(sb.from('schedule').delete().eq('id',x.id),'Bloque eliminado.')}>Eliminar</button></div>{ed?.id===x.id&&<BlockForm x={x} progs={d.p} done={done}/>}</div>)}</div>})}</>}</Async></div>}
function ProgramEdit({slug}){const[v,setV]=useState(0),s=useData(async()=>{const r=await sb.from('programs').select('*').eq('slug',slug).maybeSingle();if(r.error)throw r.error;return r.data},[v])
 return <div><h3>Meraki Fútbol: logo, nombre, descripción, redes y texto</h3><Async s={s}>{x=><ProgramForm key={v} x={x} done={()=>setV(y=>y+1)}/>}</Async></div>}
function AfaLogo(){const[logo,setLogo]=useState(null),[busy,setBusy]=useState(false),[m,setM]=useState(null)
 async function save(e){e.preventDefault();if(busy||!logo)return setM({err:1,t:'Elegí una imagen y esperá a que se suba.'});setBusy(true);const{error}=await sb.from('site_settings').upsert({key:'afa_logo',value:logo});setBusy(false);setM(error?{err:1,t:error.message}:{t:'Logo de AFA guardado ✔'})}
 return <form onSubmit={save}><h3>AFA: logo de la sección</h3><p className="muted">Las noticias de AFA se publican desde Nueva noticia, con categoría "afa".</p><Img onUrl={setLogo} label="Logo de la AFA" max={800}/><Msg m={m}/><p><button className="btn" disabled={busy} style={{border:0,cursor:'pointer'}}>{busy?'Guardando…':'Guardar'}</button></p></form>}
function QuienesAdmin(){const[v,setV]=useState(0),[sel,setSel]=useState('radio'),[busy,setBusy]=useState(false),[m,setM]=useState(null),s=useData(async()=>{const[p,r]=await Promise.all([sb.from('programs').select('id,nombre,quienes_somos').order('orden'),sb.from('radio_settings').select('key,value').eq('key','quienes_somos')]);if(p.error)throw p.error;if(r.error)throw r.error;return{p:p.data,r:r.data[0]?.value||''}},[v])
 async function save(e){e.preventDefault();if(busy)return;const t=new FormData(e.target).get('t')||'';setBusy(true);setM(null)
  const{error}=await(sel==='radio'?sb.from('radio_settings').upsert({key:'quienes_somos',value:t}):sb.from('programs').update({quienes_somos:t||null}).eq('id',sel));setBusy(false);if(error)return setM({err:1,t:error.message});setM({t:'Guardado ✔'});setV(x=>x+1)}
 return <Async s={s}>{d=>{const cur=sel==='radio'?d.r:(d.p.find(x=>x.id===sel)?.quienes_somos||'');return <form onSubmit={save}><h3>¿Quiénes somos?</h3><label>¿Quiénes somos de:</label><select value={sel} onChange={e=>setSel(e.target.value)}><option value="radio">FM Meraki</option>{d.p.map(x=><option key={x.id} value={x.id}>{x.nombre}</option>)}</select><label>Texto</label><textarea name="t" rows="9" key={sel+'-'+v} defaultValue={cur}/><Msg m={m}/><p><button className="btn" disabled={busy} style={{border:0,cursor:'pointer'}}>{busy?'Guardando…':'Guardar texto'}</button></p></form>}}</Async>}
const AREAS={f:['Meraki Fútbol',[['n','Nueva noticia'],['c','Nueva crónica'],['k','Clubes'],['w','Cronistas'],['i','Entrevista'],['o','Contenido'],['a','AFA (logo)'],['mf','Logo, redes e info']]],r:['FM Meraki',[['rp','Programas'],['rg','Grilla'],['rc','Radio FM Meraki']]],t:['Textos y sitio',[['q','¿Quiénes somos?']]],s:['📊 Estadísticas',[['st','Resumen']]]}
export default function Admin(){useTitle('Admin');const[s,setS]=useState({loading:true}),[tab,setTab]=useState('n'),[area,setArea]=useState('f'),[e,setE]=useState(null),[busy,setBusy]=useState(false)
 useEffect(()=>{const chk=async ses=>{if(!ses)return setS({});const{data,error}=await sb.rpc('is_admin');setS({user:ses.user,admin:data===true,error:error?.message})}
  sb.auth.getSession().then(({data})=>chk(data.session));const{data:l}=sb.auth.onAuthStateChange((_,ses)=>setTimeout(()=>chk(ses),0));return()=>l.subscription.unsubscribe()},[])
 async function login(ev){ev.preventDefault();setBusy(true);setE(null);const f=ev.target.elements;const{error}=await sb.auth.signInWithPassword({email:f.email.value,password:f.pass.value});setBusy(false);if(error)setE(error.message)}
 if(s.loading)return <div className="w"><p className="muted">Cargando…</p></div>
 if(!s.user)return <div className="w art"><h1>Admin</h1><form onSubmit={login}><label>Email</label><input name="email" type="email" required autoComplete="email"/><label>Contraseña</label><input name="pass" type="password" required autoComplete="current-password"/>{e&&<p className="err">{e}</p>}<p><button className="btn" disabled={busy} style={{border:0}}>{busy?'Ingresando…':'Iniciar sesión'}</button></p></form><Link to="/">← Volver a la web</Link></div>
 if(!s.admin)return <div className="w art"><h1>Sin permisos</h1><p className="err">{s.error||'Esta cuenta no es administradora.'}</p><button className="btn" onClick={()=>sb.auth.signOut()}>Cerrar sesión</button></div>
 return <div className="w art"><h1>Panel de administración</h1><div className="tabs">{Object.entries(AREAS).map(([k,[nm,sb2]])=><button key={k} className={'tag'+(area===k?' on':'')} onClick={()=>{setArea(k);setTab(sb2[0][0])}}>{nm}</button>)}<button className="tag" onClick={()=>sb.auth.signOut()}>Cerrar sesión</button></div>
  <div className="tabs" style={{marginTop:-4}}>{AREAS[area][1].map(([k,nm])=><button key={k} className={'tag'+(tab===k?' on':'')} style={{opacity:tab===k?1:.75}} onClick={()=>setTab(k)}>{nm}</button>)}</div>
  {tab==='n'?<NewsEditor/>:tab==='c'?<ChrForm/>:tab==='k'?<ClubsAdmin/>:tab==='w'?<WritersAdmin/>:tab==='i'?<InterviewForm/>:tab==='o'?<ContentAdmin/>:tab==='a'?<AfaLogo/>:tab==='mf'?<ProgramEdit slug="meraki-futbol"/>:tab==='rp'?<ProgramsAdmin/>:tab==='rg'?<ScheduleAdmin/>:tab==='rc'?<RadioAdmin/>:tab==='st'?<StatsAdmin/>:<QuienesAdmin/>}</div>}
