import {useEffect,useState} from 'react'
import {Link,useNavigate} from 'react-router-dom'
import {sb} from './supabase'
import {optimizeImage,fmt} from './imagen'
import {api} from './api'
import {Async,useData,useTitle,slugify} from './ui'
function Img({onUrl,label,max}){const[p,setP]=useState(null),[st,setSt]=useState('')
 async function pick(e){const f0=e.target.files[0];if(!f0)return;onUrl(null);setP(null);setSt('Optimizando imagen…')
  let r;try{r=await optimizeImage(f0,{maxSide:max||1600})}catch(er){e.target.value='';return setSt('Error: '+er.message)}
  setP(URL.createObjectURL(r.file));setSt('Subiendo imagen…')
  const path=`${Date.now()}-${r.file.name.replace(/[^a-z0-9.]+/gi,'-')}`,{error}=await sb.storage.from('imagenes').upload(path,r.file,{contentType:r.file.type})
  if(error)return setSt('Error al subir la imagen: '+error.message)
  onUrl(sb.storage.from('imagenes').getPublicUrl(path).data.publicUrl);setSt(r.changed?`Imagen optimizada (${fmt(r.before)} → ${fmt(r.after)}) y subida ✔`:'Imagen subida ✔')}
 return <><label>{label||'Imagen principal'}</label><input type="file" accept="image/*" onChange={pick}/>{p&&<img src={p} alt="Vista previa" style={{maxWidth:'100%',maxHeight:180,marginTop:8}}/>}<small className="muted">{st}</small></>}
const Opts=({l,v='id',t='nombre'})=>l.map(x=><option key={x[v]} value={x[v]}>{x[t]}</option>)
const Msg=({m})=>m?<p className={m.err?'err':''} style={m.err?null:{color:'#7ee39a'}}>{m.t}</p>:null
function NewsForm(){const o=useData(()=>Promise.all([api.clubs(),api.writers(),api.tournaments()])),[img,setImg]=useState(null),[busy,setBusy]=useState(false),[m,setM]=useState(null)
 async function save(e){e.preventDefault();if(busy)return;const fm=e.target,f=new FormData(fm);setBusy(true);setM(null)
  const titulo=f.get('t').trim(),slug=slugify(f.get('slug')||titulo)
  const{data,error}=await sb.from('news').insert({titulo,slug,bajada:f.get('b'),contenido:f.get('c'),imagen_url:img,categoria:f.get('cat'),tournament_id:f.get('to')||null,writer_id:f.get('w')||null,fecha:f.get('d')?new Date(f.get('d')).toISOString():new Date().toISOString(),estado:f.get('est')}).select('id').single()
  if(error){setBusy(false);return setM({err:1,t:error.code==='23505'?'Ya existe una noticia con ese slug.':error.message})}
  const cl=f.getAll('cl');if(cl.length){const r=await sb.from('news_clubs').insert(cl.map(club_id=>({news_id:data.id,club_id})));if(r.error){setBusy(false);return setM({err:1,t:'Noticia guardada, pero fallaron los clubes: '+r.error.message})}}
  setBusy(false);fm.reset();setImg(null);setM({t:`Noticia guardada (${f.get('est')}). URL: /noticias/${slug}`})}
 return <Async s={o}>{([cl,wr,to])=><form onSubmit={save}><h3>Nueva noticia</h3><label>Título</label><input name="t" required/><label>Slug (opcional)</label><input name="slug"/><label>Bajada</label><input name="b"/><label>Contenido</label><textarea name="c" rows="6" required/><Img onUrl={setImg}/>
  <label>Categoría</label><select name="cat"><option value="general">general</option><option value="primera">primera</option><option value="ascenso">ascenso</option><option value="copas">copas</option><option value="afa">afa</option></select>
  <label>Torneo (opcional)</label><select name="to"><option value="">—</option><Opts l={to}/></select><label>Redactor (opcional)</label><select name="w"><option value="">—</option><Opts l={wr} t="nombre_visible"/></select>
  <label>Fecha (vacío = ahora)</label><input name="d" type="datetime-local"/><label>Clubes relacionados (varios)</label><select name="cl" multiple><Opts l={cl}/></select>
  <label>Estado</label><select name="est"><option value="borrador">borrador</option><option value="publicada">publicada</option></select><Msg m={m}/><p><button className="btn" disabled={busy} style={{border:0,cursor:'pointer'}}>{busy?'Guardando…':'Guardar'}</button></p></form>}</Async>}
function ChrForm(){const nav=useNavigate(),o=useData(()=>Promise.all([api.clubs(),api.writers(),api.tournaments()])),[img,setImg]=useState(null),[w,setW]=useState(''),[busy,setBusy]=useState(false),[m,setM]=useState(null)
 function onHome(e,wr){const x=wr.find(r=>r.club_id===e.target.value);if(x)setW(x.id)} // sugerencia: cronista del local
 async function save(e){e.preventDefault();if(busy)return;const f=new FormData(e.target);if(f.get('h')===f.get('a'))return setM({err:1,t:'Local y visitante deben ser distintos.'});if(!w)return setM({err:1,t:'Elegí un redactor.'});if(img===null&&e.target.querySelector('input[type=file]').files.length)return setM({err:1,t:'Esperá a que termine de subir la imagen.'})
  setBusy(true);setM(null)
  const{data,error}=await sb.rpc('publish_chronicle',{p_tournament:f.get('to'),p_fecha_numero:f.get('n')?+f.get('n'):null,p_fecha:f.get('d')?new Date(f.get('d')).toISOString():null,p_home:f.get('h'),p_away:f.get('a'),p_hg:+f.get('hg'),p_ag:+f.get('ag'),p_writer:w,p_titulo:f.get('t'),p_bajada:f.get('b'),p_contenido:f.get('c'),p_imagen:img,p_estado:f.get('est')})
  setBusy(false);if(error)return setM({err:1,t:error.message.includes('ya tiene una crónica')?'Este partido ya tiene una crónica.':error.message});nav('/cronicas/'+data)}
 return <Async s={o}>{([cl,wr,to])=><form onSubmit={save}><h3>Nueva crónica</h3><label>Torneo</label><select name="to" required><Opts l={to}/></select><label>Número de fecha</label><input name="n" type="number" min="1"/><label>Fecha/hora del partido</label><input name="d" type="datetime-local"/>
  <label>Equipo local</label><select name="h" required defaultValue="" onChange={e=>onHome(e,wr)}><option value="" disabled>Elegir…</option><Opts l={cl}/></select><label>Equipo visitante</label><select name="a" required defaultValue=""><option value="" disabled>Elegir…</option><Opts l={cl}/></select>
  <label>Goles local / visitante</label><div style={{display:'flex',gap:8}}><input name="hg" type="number" min="0" defaultValue="0" required/><input name="ag" type="number" min="0" defaultValue="0" required/></div>
  <label>Redactor (único; se sugiere el del local, podés cambiarlo)</label><select value={w} onChange={e=>setW(e.target.value)} required><option value="" disabled>Elegir…</option><Opts l={wr} t="nombre_visible"/></select>
  <label>Título</label><input name="t" required/><label>Bajada</label><input name="b"/><label>Contenido</label><textarea name="c" rows="6" required/><Img onUrl={setImg}/><label>Estado</label><select name="est"><option value="publicada">publicada</option><option value="borrador">borrador</option></select>
  <Msg m={m}/><p><button className="btn" disabled={busy} style={{border:0,cursor:'pointer'}}>{busy?'Publicando…':'Publicar'}</button></p></form>}</Async>}
async function upImg(file){const r=await optimizeImage(file,{maxSide:600});const path=`escudos/${Date.now()}-${r.file.name.replace(/[^a-z0-9.]+/gi,'-')}`,{error}=await sb.storage.from('imagenes').upload(path,r.file,{contentType:r.file.type});if(error)throw error;return sb.storage.from('imagenes').getPublicUrl(path).data.publicUrl}
function ClubsAdmin(){const[v,setV]=useState(0),s=useData(api.clubs,[v]),[img,setImg]=useState(null),[busy,setBusy]=useState(false),[m,setM]=useState(null)
 async function add(e){e.preventDefault();if(busy)return;const fm=e.target,f=new FormData(fm);setBusy(true);setM(null);const nombre=f.get('n').trim()
  const{error}=await sb.from('clubs').insert({nombre,slug:slugify(f.get('s')||nombre),ciudad:f.get('c'),estadio:f.get('e'),escudo_url:img});setBusy(false)
  if(error)return setM({err:1,t:error.code==='23505'?'Ya existe un club con ese slug.':error.message});fm.reset();setImg(null);setM({t:'Club guardado.'});setV(x=>x+1)}
 async function del(c){if(!confirm(`¿Eliminar el club "${c.nombre}"?`))return;const{error}=await sb.from('clubs').delete().eq('id',c.id);if(error)return setM({err:1,t:error.code==='23503'?'Este club tiene crónicas o partidos. Eliminalas primero en la pestaña Contenido.':error.message});setM({t:'Club eliminado.'});setV(x=>x+1)}
 async function escudo(c,file){if(!file)return;setM({t:`Optimizando y subiendo escudo de ${c.nombre}…`});try{const url=await upImg(file);const{error}=await sb.from('clubs').update({escudo_url:url}).eq('id',c.id);if(error)throw error;setM({t:`Escudo de ${c.nombre} guardado ✔`});setV(x=>x+1)}catch(er){setM({err:1,t:'Error: '+er.message})}}
 return <div><h3>Clubes y escudos</h3><Msg m={m}/><Async s={s} empty="No hay clubes cargados.">{l=>l.map(c=><div key={c.id} style={{display:'flex',gap:10,alignItems:'center',padding:'8px 0',borderBottom:'1px solid var(--line)'}}>{c.escudo_url?<img src={c.escudo_url} width="32" height="36" alt="" style={{objectFit:'contain'}}/>:<span className="shield" style={{'--c':'#1f6b3a',width:32,height:36}}/>}<span style={{flex:1}}>{c.nombre}{c.es_demo?' (demo)':''}</span><label className="tag" style={{cursor:'pointer',margin:0}}>Cambiar escudo<input type="file" accept="image/*" style={{display:'none'}} onChange={e=>escudo(c,e.target.files[0])}/></label><button className="tag" onClick={()=>del(c)}>Eliminar</button></div>)}</Async>
 <form onSubmit={add}><h3 style={{marginTop:20}}>Nuevo club</h3><label>Nombre</label><input name="n" required/><label>Slug (opcional)</label><input name="s"/><label>Ciudad</label><input name="c"/><label>Estadio</label><input name="e"/><Img onUrl={setImg} label="Escudo" max={600}/><p><button className="btn" disabled={busy} style={{border:0,cursor:'pointer'}}>{busy?'Guardando…':'Guardar club'}</button></p></form></div>}
function WritersAdmin(){const[v,setV]=useState(0),o=useData(()=>Promise.all([api.clubs(),api.writers()]),[v]),[busy,setBusy]=useState(false),[m,setM]=useState(null)
 async function add(e){e.preventDefault();if(busy)return;const fm=e.target,f=new FormData(fm);setBusy(true);setM(null);const n=f.get('n').trim(),a=f.get('a').trim()
  const{error}=await sb.from('writers').insert({nombre:n,apellido:a,nombre_visible:(f.get('v')||`${n} ${a}`).trim(),club_id:f.get('c')||null,descripcion:f.get('d')});setBusy(false)
  if(error)return setM({err:1,t:error.message});fm.reset();setM({t:'Cronista guardado.'});setV(x=>x+1)}
 async function delW(w){if(!confirm(`¿Eliminar a ${w.nombre_visible}?`))return;const{error}=await sb.from('writers').delete().eq('id',w.id);if(error)return setM({err:1,t:error.code==='23503'?'Este cronista tiene crónicas. Eliminalas primero en Contenido.':error.message});setV(x=>x+1)}
 return <Async s={o}>{([cl,wr])=><div><h3>Cronistas</h3><form onSubmit={add}><label>Nombre</label><input name="n" required/><label>Apellido</label><input name="a" required/><label>Nombre visible (opcional)</label><input name="v"/><label>Club del que es cronista</label><select name="c"><option value="">—</option><Opts l={cl}/></select><label>Descripción (opcional)</label><input name="d"/><Msg m={m}/><p><button className="btn" disabled={busy} style={{border:0,cursor:'pointer'}}>{busy?'Guardando…':'Guardar cronista'}</button></p></form><h3>Cargados</h3>{wr.map(w=><div key={w.id} style={{display:'flex',gap:8,alignItems:'center',padding:'6px 0'}}><span style={{flex:1}}>{w.nombre_visible}{w.es_demo?' (demo)':''} — {cl.find(c=>c.id===w.club_id)?.nombre||'sin club'}</span><button className="tag" onClick={()=>delW(w)}>Eliminar</button></div>)}</div>}</Async>}
function EditForm({t,x,done}){const[img,setImg]=useState(null),[busy,setBusy]=useState(false),[m,setM]=useState(null)
 async function save(e){e.preventDefault();if(busy)return;const f=new FormData(e.target);setBusy(true);setM(null)
  const u={titulo:f.get('t'),bajada:f.get('b'),contenido:f.get('c'),estado:f.get('e')};if(img)u.imagen_url=img
  if(t==='c'&&u.estado==='publicada'&&!x.publicada_at)u.publicada_at=new Date().toISOString()
  const{error}=await sb.from(t==='n'?'news':'chronicles').update(u).eq('id',x.id);setBusy(false);if(error)return setM({err:1,t:error.message});done()}
 return <form onSubmit={save} style={{background:'var(--bg2)',padding:12,margin:'8px 0'}}><label>Título</label><input name="t" defaultValue={x.titulo} required/><label>Bajada</label><input name="b" defaultValue={x.bajada||''}/><label>Contenido</label><textarea name="c" rows="8" defaultValue={x.contenido||''}/><Img onUrl={setImg} label="Cambiar imagen (opcional)"/><label>Estado</label><select name="e" defaultValue={x.estado}><option value="borrador">borrador</option><option value="publicada">publicada</option></select><Msg m={m}/><p><button className="btn" disabled={busy} style={{border:0,cursor:'pointer'}}>{busy?'Guardando…':'Guardar cambios'}</button> <button type="button" className="tag" onClick={done}>Cancelar</button></p></form>}
function ContentAdmin(){const[v,setV]=useState(0),[m,setM]=useState(null),[ed,setEd]=useState(null),s=useData(async()=>{const[n,c]=await Promise.all([sb.from('news').select('*').order('created_at',{ascending:false}).limit(50),sb.from('chronicles').select('*').order('created_at',{ascending:false}).limit(50)]);if(n.error)throw n.error;if(c.error)throw c.error;return{n:n.data,c:c.data}},[v])
 async function run(p,ok){const{error}=await p;if(error)return setM({err:1,t:error.message});setM({t:ok});setV(x=>x+1)}
 const del=(t,x)=>confirm(`¿Eliminar "${x.titulo}"? No se puede deshacer.`)&&run(t==='n'?sb.from('news').delete().eq('id',x.id):sb.from('matches').delete().eq('id',x.match_id),'Eliminado.')
 const tog=x=>run(sb.from('news').update({estado:x.estado==='publicada'?'borrador':'publicada'}).eq('id',x.id),'Estado actualizado.')
 const row=(x,t)=><div key={x.id}><div style={{display:'flex',gap:8,alignItems:'center',flexWrap:'wrap',padding:'8px 0',borderBottom:'1px solid var(--line)'}}><span style={{flex:1,minWidth:150}}>{x.titulo} <small className="muted">({x.estado})</small></span><button className="tag" onClick={()=>setEd(ed?.x.id===x.id?null:{t,x})}>Editar</button>{t==='n'&&<button className="tag" onClick={()=>tog(x)}>{x.estado==='publicada'?'Pasar a borrador':'Publicar'}</button>}<button className="tag" onClick={()=>del(t,x)}>Eliminar</button></div>{ed?.x.id===x.id&&<EditForm t={t} x={x} done={()=>{setEd(null);setV(y=>y+1)}}/>}</div>
 return <div><h3>Noticias</h3><Msg m={m}/><Async s={s}>{d=><>{d.n.map(x=>row(x,'n'))}{!d.n.length&&<p className="muted">No hay noticias.</p>}<h3 style={{marginTop:20}}>Crónicas</h3>{d.c.map(x=>row(x,'c'))}{!d.c.length&&<p className="muted">No hay crónicas.</p>}</>}</Async></div>}
function InterviewForm(){const[img,setImg]=useState(null),[busy,setBusy]=useState(false),[m,setM]=useState(null)
 async function save(e){e.preventDefault();if(busy)return;const fm=e.target,f=new FormData(fm);setBusy(true);setM(null);const titulo=f.get('t').trim(),slug=slugify(titulo)
  const{error}=await sb.from('interviews').insert({titulo,slug,bajada:f.get('b'),contenido:f.get('c'),imagen_url:img,entrevistado:f.get('p'),tipo_entrevistado:f.get('k'),enlace_url:f.get('l')||null,estado:f.get('e')});setBusy(false)
  if(error)return setM({err:1,t:error.code==='23505'?'Ya existe una entrevista con ese título.':error.message});fm.reset();setImg(null);setM({t:'Entrevista guardada. URL: /entrevistas/'+slug})}
 return <form onSubmit={save}><h3>Nueva entrevista</h3><label>Título</label><input name="t" required/><label>Entrevistado/a</label><input name="p" required/><label>Tipo</label><select name="k"><option value="jugador">jugador</option><option value="entrenador">entrenador</option><option value="dirigente">dirigente</option><option value="periodista">periodista</option><option value="otra">otra personalidad</option></select><label>Link de la entrevista (YouTube, etc.)</label><input name="l" placeholder="https://..."/><label>Bajada</label><input name="b"/><label>Texto (opcional)</label><textarea name="c" rows="5"/><Img onUrl={setImg}/><label>Estado</label><select name="e"><option value="publicada">publicada</option><option value="borrador">borrador</option></select><Msg m={m}/><p><button className="btn" disabled={busy} style={{border:0,cursor:'pointer'}}>{busy?'Guardando…':'Guardar entrevista'}</button></p></form>}
const KEYS=[['quienes_somos','Texto de ¿Quiénes somos?',1],['afa_texto','Texto de la página AFA',1],['youtube_url','Link del canal de YouTube',0],['instagram_url','Link de Instagram',0],['tiktok_url','Link de TikTok',0],['x_url','Link de X (Twitter)',0],['facebook_url','Link de Facebook',0]]
function SettingsAdmin(){const[v,setV]=useState(0),s=useData(api.settings,[v]),[busy,setBusy]=useState(false),[m,setM]=useState(null),[logo,setLogo]=useState(null)
 async function save(e){e.preventDefault();if(busy)return;const f=new FormData(e.target);setBusy(true);setM(null);const rows=KEYS.map(([k])=>({key:k,value:f.get(k)||''}));if(logo)rows.push({key:'afa_logo',value:logo})
  const{error}=await sb.from('site_settings').upsert(rows);setBusy(false);if(error)return setM({err:1,t:error.message});setM({t:'Guardado ✔'});setV(x=>x+1)}
 return <Async s={s}>{c=><form onSubmit={save} key={v}><h3>Textos y sitio</h3>{KEYS.map(([k,l,big])=><div key={k}><label>{l}</label>{big?<textarea name={k} rows="5" defaultValue={c[k]||''}/>:<input name={k} defaultValue={c[k]||''} placeholder="https://..."/>}</div>)}<Img onUrl={setLogo} label="Logo de la AFA" max={800}/>{c.afa_logo&&<p className="muted">Ya hay un logo cargado. Si subís otro, lo reemplaza.</p>}<Msg m={m}/><p><button className="btn" disabled={busy} style={{border:0,cursor:'pointer'}}>{busy?'Guardando…':'Guardar'}</button></p></form>}</Async>}
export default function Admin(){useTitle('Admin');const[s,setS]=useState({loading:true}),[tab,setTab]=useState('n'),[e,setE]=useState(null),[busy,setBusy]=useState(false)
 useEffect(()=>{const chk=async ses=>{if(!ses)return setS({});const{data,error}=await sb.rpc('is_admin');setS({user:ses.user,admin:data===true,error:error?.message})}
  sb.auth.getSession().then(({data})=>chk(data.session));const{data:l}=sb.auth.onAuthStateChange((_,ses)=>setTimeout(()=>chk(ses),0));return()=>l.subscription.unsubscribe()},[])
 async function login(ev){ev.preventDefault();setBusy(true);setE(null);const f=ev.target.elements;const{error}=await sb.auth.signInWithPassword({email:f.email.value,password:f.pass.value});setBusy(false);if(error)setE(error.message)}
 if(s.loading)return <div className="w"><p className="muted">Cargando…</p></div>
 if(!s.user)return <div className="w art"><h1>Admin</h1><form onSubmit={login}><label>Email</label><input name="email" type="email" required autoComplete="email"/><label>Contraseña</label><input name="pass" type="password" required autoComplete="current-password"/>{e&&<p className="err">{e}</p>}<p><button className="btn" disabled={busy} style={{border:0}}>{busy?'Ingresando…':'Iniciar sesión'}</button></p></form><Link to="/">← Volver a la web</Link></div>
 if(!s.admin)return <div className="w art"><h1>Sin permisos</h1><p className="err">{s.error||'Esta cuenta no es administradora.'}</p><button className="btn" onClick={()=>sb.auth.signOut()}>Cerrar sesión</button></div>
 return <div className="w art"><h1>Panel de administración</h1><div className="tabs"><button className={'tag'+(tab==='n'?' on':'')} onClick={()=>setTab('n')}>Nueva noticia</button><button className={'tag'+(tab==='c'?' on':'')} onClick={()=>setTab('c')}>Nueva crónica</button><button className={'tag'+(tab==='i'?' on':'')} onClick={()=>setTab('i')}>Entrevista</button><button className={'tag'+(tab==='k'?' on':'')} onClick={()=>setTab('k')}>Clubes</button><button className={'tag'+(tab==='w'?' on':'')} onClick={()=>setTab('w')}>Cronistas</button><button className={'tag'+(tab==='o'?' on':'')} onClick={()=>setTab('o')}>Contenido</button><button className={'tag'+(tab==='s'?' on':'')} onClick={()=>setTab('s')}>Textos y sitio</button><button className="tag" onClick={()=>sb.auth.signOut()}>Cerrar sesión</button></div>
  {tab==='n'?<NewsForm/>:tab==='c'?<ChrForm/>:tab==='i'?<InterviewForm/>:tab==='k'?<ClubsAdmin/>:tab==='w'?<WritersAdmin/>:tab==='o'?<ContentAdmin/>:<SettingsAdmin/>}<p className="muted">Pendiente: formulario de actualizaciones de Ascenso y editar entrevistas.</p></div>}
