import {Link,useSearchParams} from 'react-router-dom'
import {api} from './api'
import {Async,useData,Page,Sec,Grid,NewsCard,ChrCard,ClubCard,MatchRow,Table,fdate} from './ui'
const Tabs=({k})=><div className="tabs">{[['cronicas','Crónicas'],['clubes','Clubes']].map(([x,l])=><Link key={x} className={'tag'+(x===k?' on':'')} to={'/'+x}>{l}</Link>)}</div>
export const Cronicas=()=>{const s=useData(api.chronicles);return <Page title="Crónicas"><Tabs k="cronicas"/><Async s={s} empty="No hay crónicas publicadas todavía.">{l=><Grid>{l.map(ChrCard)}</Grid>}</Async></Page>}
export const Clubes=()=>{const s=useData(api.clubs);return <Page title="Clubes"><Tabs k="clubes"/><Async s={s} empty="Todavía no hay clubes cargados.">{l=><div className="clubs">{l.map(ClubCard)}</div>}</Async></Page>}
export const Resultados=()=>{const s=useData(api.matches);return <Page title="Resultados"><Tabs k="resultados"/><Async s={s} empty="No hay partidos cargados.">{l=>l.map(m=><div key={m.id}><small className="muted">{m.tournaments.nombre}{m.fecha_numero?` · Fecha ${m.fecha_numero}`:''} · {m.estado}</small><MatchRow m={m}/></div>)}</Async></Page>}
export const Tablas=()=>{const s=useData(api.standings);return <Page title="Tablas"><Tabs k="tablas"/><Async s={s} empty="No hay tablas cargadas.">{l=>[...new Set(l.map(r=>r.tournaments.nombre))].map(t=><div key={t}><Sec t={t}/>{[...new Set(l.filter(r=>r.tournaments.nombre===t).map(r=>r.zona||''))].sort().map(z=><div key={z}>{z&&<h3 style={{margin:'14px 0 8px',fontSize:15}}>{z}</h3>}<Table rows={l.filter(r=>r.tournaments.nombre===t&&(r.zona||'')===z)}/></div>)}</div>)}</Async></Page>}
export const AscensoList=()=>{const s=useData(api.updates);return <Page title="Ascenso"><Async s={s} empty="No hay actualizaciones de Ascenso publicadas todavía.">{l=><Grid>{l.map(u=><Link key={u.id} className="card" to={`/ascenso/${u.slug}`}><div className="b"><span className="tag">Fecha {u.numero_fecha}</span><h3>{u.titulo}</h3><small>{fdate(u.fecha)}</small></div></Link>)}</Grid>}</Async></Page>}
export const Copas=()=>{const s=useData(async()=>{const[t,n,m]=await Promise.all([api.tournaments(),api.news('copas'),api.matches()]);const c=t.filter(x=>x.tipo==='copa');return{c,n,m:m.filter(x=>c.some(y=>y.id===x.tournament_id))}});
 return <Page title="Copas"><Async s={s}>{d=><>{d.c.length===0&&<p className="muted">No hay copas cargadas.</p>}{d.c.map(t=><div key={t.id}><Sec t={t.nombre}/>{d.m.filter(x=>x.tournament_id===t.id).map(m=><MatchRow key={m.id} m={m}/>)}</div>)}<Sec t="Noticias"/>{d.n.length?<Grid>{d.n.map(NewsCard)}</Grid>:<p className="muted">No hay noticias de copas todavía.</p>}</>}</Async></Page>}
export const Afa=()=>{const s=useData(()=>api.news('afa'));return <Page title="AFA"><Async s={s} empty="No hay noticias de AFA publicadas todavía.">{l=><Grid>{l.map(NewsCard)}</Grid>}</Async></Page>}
export const Entrevistas=()=>{const s=useData(api.interviews);return <Page title="Entrevistas"><Async s={s} empty="No hay entrevistas publicadas todavía.">{l=><Grid>{l.map(i=><Link key={i.id} className="card" to={`/entrevistas/${i.slug}`}><div className="b"><span className="tag">{i.tipo_entrevistado}</span><h3>{i.titulo}</h3><small>{i.entrevistado}</small></div></Link>)}</Grid>}</Async></Page>}
export const Buscar=()=>{const[p]=useSearchParams(),q=p.get('q')||'';const s=useData(()=>api.search(q),[q]);return <Page title={`Resultados para “${q}”`}><Async s={s} empty="Sin resultados.">{l=><Grid>{l.map(NewsCard)}</Grid>}</Async></Page>}
export const Quienes=()=><Page title="¿Quiénes somos?"><p className="muted">[Contenido provisional editable] Meraki Fútbol es un medio digital de fútbol argentino. El texto institucional lo define el equipo.</p></Page>
export const NotFound=()=><Page title="404"><p>Página no encontrada.</p></Page>
